"""
SDEX Trading Integration Tests for Stellar MCP Server
Tests orderbook queries, order placement, and order management
Generates detailed markdown report of results
"""

from datetime import datetime
from stellar_sdk import Server
from key_manager import KeyManager
from stellar_tools import (
    create_account,
    fund_account,
    get_account,
    establish_trustline,
    build_order_transaction,
    sign_transaction,
    submit_transaction,
    get_orderbook,
    get_open_orders,
    cancel_order
)

# Test configuration
HORIZON_URL = "https://horizon-testnet.stellar.org"
USDC_ISSUER = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"

# Initialize
horizon = Server(HORIZON_URL)
keys = KeyManager()

# Report data structure
report = {
    "timestamp": datetime.now().isoformat(),
    "test_name": "SDEX Trading Integration Tests",
    "results": [],
    "accounts": {},
    "summary": {"passed": 0, "failed": 0, "total": 0}
}

def add_test_result(test_name, passed, details, error=None):
    """Add a test result to the report"""
    report["results"].append({
        "test": test_name,
        "status": "✅ PASSED" if passed else "❌ FAILED",
        "details": details,
        "error": error
    })
    if passed:
        report["summary"]["passed"] += 1
    else:
        report["summary"]["failed"] += 1
    report["summary"]["total"] += 1

    # Print to console
    status = "✅ PASSED" if passed else "❌ FAILED"
    print(f"{status}: {test_name}")
    if details:
        print(f"   {details}")
    if error:
        print(f"   Error: {error}")
    print()

def generate_markdown_report():
    """Generate markdown report file"""
    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"test_reports/sdex_trading_report_{timestamp_str}.md"

    # Ensure directory exists
    import os
    os.makedirs("test_reports", exist_ok=True)

    md = []
    md.append("# SDEX Trading Integration Test Report")
    md.append(f"\n**Test Run:** {report['timestamp']}")
    md.append(f"\n**Network:** Stellar Testnet")
    md.append(f"\n**Horizon:** {HORIZON_URL}")
    md.append("\n---\n")

    # Summary
    md.append("## Summary\n")
    md.append(f"- **Total Tests:** {report['summary']['total']}")
    md.append(f"- **Passed:** {report['summary']['passed']} ✅")
    md.append(f"- **Failed:** {report['summary']['failed']} ❌")
    md.append(f"- **Success Rate:** {(report['summary']['passed'] / report['summary']['total'] * 100) if report['summary']['total'] > 0 else 0:.1f}%")
    md.append("\n---\n")

    # Test Accounts
    if report["accounts"]:
        md.append("## Test Accounts\n")
        for name, account_id in report["accounts"].items():
            md.append(f"### {name}")
            md.append(f"- **Account ID:** `{account_id}`")
            md.append(f"- **Explorer:** [View on Stellar Expert](https://stellar.expert/explorer/testnet/account/{account_id})")
            md.append("")
        md.append("---\n")

    # Test Results
    md.append("## Test Results\n")
    for i, result in enumerate(report["results"], 1):
        md.append(f"### Test {i}: {result['test']}")
        md.append(f"\n**Status:** {result['status']}\n")
        if result["details"]:
            md.append(f"**Details:** {result['details']}\n")
        if result["error"]:
            md.append(f"**Error:**")
            md.append(f"```")
            md.append(f"{result['error']}")
            md.append(f"```\n")
        md.append("")

    md.append("---\n")
    md.append(f"\n*Report generated by Stellar MCP Server test suite*")

    # Write file
    with open(filename, "w") as f:
        f.write("\n".join(md))

    return filename

print("=" * 70)
print("STELLAR MCP SERVER - SDEX TRADING INTEGRATION TESTS")
print("=" * 70)
print()

# Test 1: Create and setup Account A (Buyer)
print("Test 1: Creating Account A (Buyer)...")
try:
    result = create_account(keys)
    if "error" in result:
        add_test_result("Create Account A", False, None, result["error"])
        exit(1)

    account_a = result["account_id"]
    report["accounts"]["Account A (Buyer)"] = account_a
    add_test_result("Create Account A", True, f"Account ID: {account_a}")
except Exception as e:
    add_test_result("Create Account A", False, None, str(e))
    exit(1)

# Test 2: Create and setup Account B (Seller)
print("Test 2: Creating Account B (Seller)...")
try:
    result = create_account(keys)
    if "error" in result:
        add_test_result("Create Account B", False, None, result["error"])
        exit(1)

    account_b = result["account_id"]
    report["accounts"]["Account B (Seller)"] = account_b
    add_test_result("Create Account B", True, f"Account ID: {account_b}")
except Exception as e:
    add_test_result("Create Account B", False, None, str(e))
    exit(1)

# Test 3: Fund Account A
print("Test 3: Funding Account A...")
print("   (This may take a few seconds...)")
try:
    result = fund_account(account_a, horizon)
    if not result.get("success"):
        add_test_result("Fund Account A", False, None, result.get("error"))
        exit(1)
    add_test_result("Fund Account A", True, f"Balance: {result['balance']} XLM")
except Exception as e:
    add_test_result("Fund Account A", False, None, str(e))
    exit(1)

# Test 4: Fund Account B
print("Test 4: Funding Account B...")
print("   (This may take a few seconds...)")
try:
    result = fund_account(account_b, horizon)
    if not result.get("success"):
        add_test_result("Fund Account B", False, None, result.get("error"))
        exit(1)
    add_test_result("Fund Account B", True, f"Balance: {result['balance']} XLM")
except Exception as e:
    add_test_result("Fund Account B", False, None, str(e))
    exit(1)

# Test 5: Establish USDC trustline on Account A
print("Test 5: Establishing USDC trustline on Account A...")
try:
    result = establish_trustline(
        account_a,
        {"code": "USDC", "issuer": USDC_ISSUER},
        keys,
        horizon
    )
    if not result.get("success"):
        add_test_result("Establish Trustline A", False, None, result.get("error"))
        exit(1)
    add_test_result("Establish Trustline A", True, f"Hash: {result['hash'][:16]}...")
except Exception as e:
    add_test_result("Establish Trustline A", False, None, str(e))
    exit(1)

# Test 6: Establish USDC trustline on Account B
print("Test 6: Establishing USDC trustline on Account B...")
try:
    result = establish_trustline(
        account_b,
        {"code": "USDC", "issuer": USDC_ISSUER},
        keys,
        horizon
    )
    if not result.get("success"):
        add_test_result("Establish Trustline B", False, None, result.get("error"))
        exit(1)
    add_test_result("Establish Trustline B", True, f"Hash: {result['hash'][:16]}...")
except Exception as e:
    add_test_result("Establish Trustline B", False, None, str(e))
    exit(1)

# Test 7: Query USDC/XLM Orderbook
print("Test 7: Querying USDC/XLM orderbook...")
try:
    result = get_orderbook(
        selling_asset={"code": "USDC", "issuer": USDC_ISSUER},
        buying_asset={"type": "native"},
        horizon=horizon,
        limit=10
    )
    if "error" in result:
        add_test_result("Query Orderbook", False, None, result["error"])
    else:
        bid_count = len(result.get("bids", []))
        ask_count = len(result.get("asks", []))
        add_test_result("Query Orderbook", True, f"Bids: {bid_count}, Asks: {ask_count}")
except Exception as e:
    add_test_result("Query Orderbook", False, None, str(e))

# Test 8: Place Buy Order (Account A buys USDC with XLM)
print("Test 8: Placing buy order (Account A: Buy 10 USDC at 0.50 XLM/USDC)...")
try:
    # Build transaction
    build_result = build_order_transaction(
        account_id=account_a,
        buy_or_sell="buy",
        selling_asset={"type": "native"},
        buying_asset={"code": "USDC", "issuer": USDC_ISSUER},
        amount="10",
        price="0.50",
        horizon=horizon
    )
    if "error" in build_result:
        add_test_result("Place Buy Order", False, None, build_result["error"])
    else:
        # Sign transaction
        sign_result = sign_transaction(account_a, build_result["xdr"], keys)
        if "error" in sign_result:
            add_test_result("Place Buy Order", False, None, sign_result["error"])
        else:
            # Submit transaction
            submit_result = submit_transaction(sign_result["signed_xdr"], horizon)
            if not submit_result.get("success"):
                add_test_result("Place Buy Order", False, None, submit_result.get("error"))
            else:
                add_test_result(
                    "Place Buy Order",
                    True,
                    f"Hash: {submit_result['hash'][:16]}..., Ledger: {submit_result['ledger']}"
                )
except Exception as e:
    add_test_result("Place Buy Order", False, None, str(e))

# Test 9: Place Sell Order (Account B sells XLM for USDC)
print("Test 9: Placing sell order (Account B: Sell 100 XLM for USDC at 2.0 USDC/XLM)...")
try:
    # Build transaction
    build_result = build_order_transaction(
        account_id=account_b,
        buy_or_sell="sell",
        selling_asset={"type": "native"},
        buying_asset={"code": "USDC", "issuer": USDC_ISSUER},
        amount="100",
        price="2.0",
        horizon=horizon
    )
    if "error" in build_result:
        add_test_result("Place Sell Order", False, None, build_result["error"])
    else:
        # Sign transaction
        sign_result = sign_transaction(account_b, build_result["xdr"], keys)
        if "error" in sign_result:
            add_test_result("Place Sell Order", False, None, sign_result["error"])
        else:
            # Submit transaction
            submit_result = submit_transaction(sign_result["signed_xdr"], horizon)
            if not submit_result.get("success"):
                add_test_result("Place Sell Order", False, None, submit_result.get("error"))
            else:
                add_test_result(
                    "Place Sell Order",
                    True,
                    f"Hash: {submit_result['hash'][:16]}..., Ledger: {submit_result['ledger']}"
                )
except Exception as e:
    add_test_result("Place Sell Order", False, None, str(e))

# Test 10: Check Open Orders for Account A
print("Test 10: Checking open orders for Account A...")
try:
    result = get_open_orders(account_a, horizon)
    if "error" in result:
        add_test_result("Check Open Orders A", False, None, result["error"])
    else:
        order_count = len(result.get("offers", []))
        add_test_result("Check Open Orders A", True, f"Found {order_count} open order(s)")

        # Store first offer ID for cancellation test
        if order_count > 0:
            report["offer_id_a"] = result["offers"][0]["id"]
except Exception as e:
    add_test_result("Check Open Orders A", False, None, str(e))

# Test 11: Check Open Orders for Account B
print("Test 11: Checking open orders for Account B...")
try:
    result = get_open_orders(account_b, horizon)
    if "error" in result:
        add_test_result("Check Open Orders B", False, None, result["error"])
    else:
        order_count = len(result.get("offers", []))
        add_test_result("Check Open Orders B", True, f"Found {order_count} open order(s)")

        # Store first offer ID for cancellation test
        if order_count > 0:
            report["offer_id_b"] = result["offers"][0]["id"]
except Exception as e:
    add_test_result("Check Open Orders B", False, None, str(e))

# Test 12: Cancel Order from Account A (if exists)
print("Test 12: Canceling order from Account A...")
if "offer_id_a" in report:
    try:
        result = cancel_order(account_a, report["offer_id_a"], keys, horizon)
        if not result.get("success"):
            add_test_result("Cancel Order A", False, None, result.get("error"))
        else:
            add_test_result(
                "Cancel Order A",
                True,
                f"Offer {report['offer_id_a']} cancelled, Hash: {result['hash'][:16]}..."
            )
    except Exception as e:
        add_test_result("Cancel Order A", False, None, str(e))
else:
    add_test_result("Cancel Order A", False, "No order to cancel", "No open orders found")

# Test 13: Cancel Order from Account B (if exists)
print("Test 13: Canceling order from Account B...")
if "offer_id_b" in report:
    try:
        result = cancel_order(account_b, report["offer_id_b"], keys, horizon)
        if not result.get("success"):
            add_test_result("Cancel Order B", False, None, result.get("error"))
        else:
            add_test_result(
                "Cancel Order B",
                True,
                f"Offer {report['offer_id_b']} cancelled, Hash: {result['hash'][:16]}..."
            )
    except Exception as e:
        add_test_result("Cancel Order B", False, None, str(e))
else:
    add_test_result("Cancel Order B", False, "No order to cancel", "No open orders found")

# Test 14: Verify Orders Cancelled
print("Test 14: Verifying orders cancelled...")
try:
    result_a = get_open_orders(account_a, horizon)
    result_b = get_open_orders(account_b, horizon)

    orders_a = len(result_a.get("offers", []))
    orders_b = len(result_b.get("offers", []))

    if orders_a == 0 and orders_b == 0:
        add_test_result("Verify Cancellation", True, "All orders successfully cancelled")
    else:
        add_test_result(
            "Verify Cancellation",
            False,
            f"Account A: {orders_a} orders, Account B: {orders_b} orders remaining",
            "Orders still exist after cancellation"
        )
except Exception as e:
    add_test_result("Verify Cancellation", False, None, str(e))

# Test 15: Execute REAL market trade - buy USDC at any price
print("Test 15: REAL MARKET BUY - Acquire USDC at market price...")
print("   (Using Account A, will pay market price in testnet XLM)")
try:
    # Query current orderbook to find best ask
    orderbook = get_orderbook(
        selling_asset={"code": "USDC", "issuer": USDC_ISSUER},
        buying_asset={"type": "native"},
        horizon=horizon,
        limit=10
    )

    if orderbook.get("asks") and len(orderbook["asks"]) > 0:
        best_ask = orderbook["asks"][0]
        ask_price = float(best_ask["price"])
        ask_amount = float(best_ask["amount"])

        # Buy amount (take a small amount to ensure we can afford it)
        buy_amount = min(ask_amount, 0.1)  # Buy 0.1 USDC or whatever is available

        print(f"   Best ask: {ask_price} XLM/USDC for {ask_amount} USDC")
        print(f"   Placing market buy: {buy_amount} USDC at {ask_price} XLM/USDC")

        # Place aggressive buy order at ask price
        build_result = build_order_transaction(
            account_id=account_a,
            buy_or_sell="buy",
            selling_asset={"type": "native"},
            buying_asset={"code": "USDC", "issuer": USDC_ISSUER},
            amount=str(buy_amount),
            price=str(ask_price),
            horizon=horizon
        )

        if "error" in build_result:
            add_test_result("Market Buy USDC", False, None, build_result["error"])
        else:
            sign_result = sign_transaction(account_a, build_result["xdr"], keys)
            submit_result = submit_transaction(sign_result["signed_xdr"], horizon)

            if not submit_result.get("success"):
                add_test_result("Market Buy USDC", False, None, submit_result.get("error"))
            else:
                # Wait for ledger and check balances
                import time
                time.sleep(3)

                account_details = get_account(account_a, horizon)
                usdc_balance = None
                xlm_balance = None

                for bal in account_details["balances"]:
                    if bal["asset_type"] == "native":
                        xlm_balance = bal["balance"]
                    elif bal.get("asset_code") == "USDC":
                        usdc_balance = float(bal["balance"])

                if usdc_balance and usdc_balance > 0:
                    add_test_result(
                        "Market Buy USDC",
                        True,
                        f"✨ REAL TRADE EXECUTED! Acquired {usdc_balance} USDC at {ask_price} XLM/USDC. XLM remaining: {xlm_balance}"
                    )
                    report["real_trade_executed"] = True
                    report["usdc_acquired"] = usdc_balance
                    report["trade_price"] = ask_price
                else:
                    add_test_result(
                        "Market Buy USDC",
                        False,
                        f"Order submitted but no USDC received. Hash: {submit_result['hash'][:16]}...",
                        "Trade may not have filled"
                    )
    else:
        add_test_result("Market Buy USDC", False, "No asks available in orderbook", "No USDC liquidity on testnet")

except Exception as e:
    add_test_result("Market Buy USDC", False, None, str(e))

print("=" * 70)
print("TEST SUITE COMPLETE")
print("=" * 70)
print()
print(f"Results: {report['summary']['passed']}/{report['summary']['total']} tests passed")
print()

# Generate markdown report
print("Generating markdown report...")
report_file = generate_markdown_report()
print(f"✅ Report saved to: {report_file}")
print()

# Print account links
print("Test Accounts:")
print(f"  Account A: https://stellar.expert/explorer/testnet/account/{account_a}")
print(f"  Account B: https://stellar.expert/explorer/testnet/account/{account_b}")
print()

# Exit with appropriate code
exit(0 if report['summary']['failed'] == 0 else 1)
